### ISSUE TITLE
Cannot read property 'start' of undefined at new EffectsRootModule

### ISSUE THREAD

**Issue by Vlad00b** [Angular-RU/universal-starter#272]
I have an ionic project for Angular 11.2.0. The project uses ngrx. I need to implement server side rendering. 
I use "@nguniversal / express-engine" for this. 
![image](https://user-images.githubusercontent.com/48056663/140810539-c5428704-c706-4b94-832b-27c93551a0e1.png)
When trying to import EffectsModule
![image](https://user-images.githubusercontent.com/48056663/140810827-f3aa5426-fec7-416f-bccb-7d2b488e7c97.png)
 I get this error
![image](https://user-images.githubusercontent.com/48056663/140810634-e63225dd-fe3d-4ff2-85d6-b3c6c1608aab.png)

**Comment by vadjs** [comment]
Ionic has many problems that makes it incompatible with SSR.
At least, I met Ionic router incompatibility with SSR.

My advice - don't try to use it with Ionic app.
